services:
    Oka\InputHandlerBundle\EventListener\AnnotationListener:
        arguments: ['@annotations.cached_reader', '@validator', '@translator']
        tags:
          - {name: kernel.event_listener, event: kernel.controller, method: onKernelController}
