services:
    oka_input_handler.request_listener:
        class: Oka\InputHandlerBundle\EventListener\RequestListener
        arguments: [[]]
        tags:
          - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255}

    oka_input_handler.annotation_listener:
        class: Oka\InputHandlerBundle\EventListener\AnnotationListener
        arguments: ['@annotations.cached_reader', '@validator', '@serializer', '@translator']
        tags:
          - {name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: -1024}

    oka_input_handler.error_response.factory:
        public: true
        class: Oka\InputHandlerBundle\Service\ErrorResponseFactory
        arguments: ['@request_stack', '@serializer']

    Oka\InputHandlerBundle\Service\ErrorResponseFactory: '@oka_input_handler.error_response.factory'
